from abc import ABC, abstractmethod
from typing import Any, Optional


class DatabaseInterface(ABC):
    @abstractmethod
    async def connect(self) -> None: ...
    @abstractmethod
    async def close(self) -> None: ...
    @abstractmethod
    async def fetch_one(self, query: str, *args) -> Optional[Any]: ...
    @abstractmethod
    async def fetch_all(self, query: str, *args) -> list[Any]: ...
    @abstractmethod
    async def execute(self, query: str, *args) -> str: ...